{% set version = "2.0.0" %}

package:
  name: mock
  version: {{ version }}

source:
  url: https://pypi.python.org/packages/source/m/mock/mock-{{ version }}.tar.gz
  sha256: b158b6df76edd239b8208d481dc46b6afd45a846b7812ff0ce58971cf5bc8bba

build:
  number: 1003
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - pbr >=1.3
  run:
    - python >=3.6
    - pbr >=1.3
    - six

test:
  imports:
    - mock

about:
  home: https://github.com/testing-cabal/mock
  license: BSD-2-Clause
  license_file: LICENSE.txt
  summary: A library for testing in Python

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
