{% set name = "mock" %}
{% set version = "5.0.1" %}

package:
  name: mock
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mock-{{ version }}.tar.gz
  sha256: e3ea505c03babf7977fd21674a69ad328053d414f05e6433c30d8fa14a534a6b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - mock

about:
  home: http://mock.readthedocs.org/en/latest/
  summary: Rolling backport of unittest.mock for all Pythons
  dev_url: https://github.com/testing-cabal/mock
  license: BSD-2-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - xylar
