{% set version = "4.0.1" %}

package:
  name: mock
  version: {{ version }}

source:
  url: https://pypi.python.org/packages/source/m/mock/mock-{{ version }}.tar.gz
  sha256: 2a572b715f09dd2f0a583d8aeb5bb67d7ed7a8fd31d193cf1227a99c16a67bc3

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - funcsigs    # [py<33]
    - six

test:
  imports:
    - mock

about:
  home: https://github.com/testing-cabal/mock
  license: BSD-2-Clause
  license_file: LICENSE.txt
  summary: A library for testing in Python

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
