{% set name = "mock" %}
{% set version = "5.1.0" %}

package:
  name: mock
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mock-{{ version }}.tar.gz
  sha256: 5e96aad5ccda4718e0a229ed94b2024df75cc2d55575ba5762d31f5767b8767d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - mock

about:
  home: http://mock.readthedocs.org/en/latest/
  summary: Rolling backport of unittest.mock for all Pythons
  dev_url: https://github.com/testing-cabal/mock
  license: BSD-2-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - xylar
