{% set name = "mock" %}
{% set version = "5.0.0" %}

package:
  name: mock
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mock-{{ version }}.tar.gz
  sha256: fd552787228eb2ab8352f270470fa93c9ad8b9cbc565c5558ee3faed8edb3853

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - six

test:
  imports:
    - mock

about:
  home: http://mock.readthedocs.org/en/latest/
  summary: Rolling backport of unittest.mock for all Pythons
  dev_url: https://github.com/testing-cabal/mock
  license: BSD-2-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - xylar
