{% set version = "5.0.0" %}

package:
  name: mock
  version: {{ version }}

source:
  url: https://pypi.python.org/packages/source/m/mock/mock-{{ version }}.tar.gz
  sha256: fd552787228eb2ab8352f270470fa93c9ad8b9cbc565c5558ee3faed8edb3853

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - six

test:
  imports:
    - mock

about:
  home: https://github.com/testing-cabal/mock
  license: BSD-2-Clause
  license_file: LICENSE.txt
  summary: A library for testing in Python

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - xylar
