{% set version = "1.0.1" %}

package:
  name: mock
  version: {{ version }}

source:
  fn: mock-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/m/mock/mock-{{ version }}.tar.gz
  sha256: b839dd2d9c117c701430c149956918a423a9863b48b09c90e30a6013e7d2f44f

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
    - funcsigs    # [py<33]
    - pbr
    - six

  run:
    - python
    - funcsigs    # [py<33]
    - pbr
    - six

test:
  imports:
    - mock

about:
  home: https://github.com/testing-cabal/mock
  license: BSD 2-Clause
  summary: A library for testing in Python.

extra:
  recipe-maintainers:
    - jakirkham
