{% set version = "1.3.0" %}

package:
  name: mock
  version: {{ version }}

source:
  fn: mock-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/m/mock/mock-{{ version }}.tar.gz
  sha256: 1e247dbecc6ce057299eb7ee019ad68314bb93152e81d9a6110d35f4d5eca0f6

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - funcsigs    # [py<33]
    - pbr
    - six

  run:
    - python
    - funcsigs    # [py<33]
    - pbr
    - six

test:
  imports:
    - mock

about:
  home: https://github.com/testing-cabal/mock
  license_file: LICENSE.txt
  license: BSD 2-Clause
  summary: A library for testing in Python.
  dev_url: https://github.com/testing-cabal/mock
  doc_url: https://docs.python.org/dev/library/unittest.mock.html

extra:
  recipe-maintainers:
    - jakirkham
