travis:
  secure:
    BINSTAR_TOKEN: UNevMoR7LSQQDOYhTqGIotpB10pA3nUN5cbHlZJ+WiI0YINoU+M0fV6EExggS0vcNnzv3fyAKQ0VjZqYR/xbaHkItSjf9hN0kRB3Nkia9SiFW9CiYirNHMjoa6zCcJT+C5WQI7Xfarftr4LmwEhP84RDadgIgEfX4sc2/AJ6GGjiDoKFOrikPfhUrtgyowtzx1ncPt7WeOvU6OKXksKz0ZsjByu2O8cBKkaF1HniavNR0IsVymP9uWridUSFOhWvrD0Wxy0hA7YCgYaqesic8jHTEoyNqGvFJHkSwxp5CV1GWPziOy485wNrGyNhuTUWLQwY70h3rBKcsl9OV4lp76Ixz+gR+fVsNjscFkvcGMUkR+Ctq4FDJcAZ8pNNp6OXSv2340EMZPvRUQFNC95hrpY1J2Go48QA/FpZhrmHkCVxA5D32CFNMIBZlRsXg+vY2/kMLDnp2/7irrVfTs3aCylzv5zdn+t/NlYqNyS6to6ZaA1/NqmzTrIXVlJRMfZxuGs3g10n+LZMs0rKMhWTmwUIyxvIm1R19ssHcF+iA9O5MoTsxjmOIYVC9wBF4dzybsB9QHvSbmM7DaLv/fplo43A85MczFBiMa+WimMMVcYI7y+XqLD2/CIQ5YOa54CE1w16xSYn+kj5JNzQcarbizQN4ssqF7E440R1MnECvcs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: true
